### ISSUE TITLE
Support conversion of `\n` to ZPL newline characters `\\&`

### ISSUE THREAD

**Issue by itsmattking** [itsmattking/k2zpl#15]
Create an extension function of `String` perhaps?

**Comment by jbduncan** [comment]
I can see at least two options:

1. Automatically translate `\n` into `\\&` behind the scenes, as part of the `build()` function perhaps.
    - Pro: This would let us use Kotlin multiline blocks and `trimIndent()`.
    - Cons:
        - It's less explicit what's happening.
        - If `\n` means something useful to the printer, we'd need a workaround to support it.
2. Make a function like `ZplBuilder.appendLine()`, à la https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/append-line.html#appendline.
    - Pro: It's explicit what's happening.
    - Con: We wouldn't be able to use Kotlin multiline blocks.
