### ISSUE TITLE
Add block helper function

### ISSUE THREAD

**Issue by itsmattking** [itsmattking/k2zpl#7]
Similar to how field helper works by automatically setting font, origin, fieldseparator, etc.

**Comment by jbduncan** [comment]
Can you give me an example of how this would help us and/or how this would look in practice?

**Comment by itsmattking** [comment]
This has already been implemented in https://github.com/sainsburys-tech/k2zpl/blob/39af7d87413f9d33cfa0f6cf3516e5e1990b34d0/src/main/kotlin/com/sainsburys/k2zpl/command/FieldBlock.kt
